### ISSUE TITLE
pandas should be in requirements.txt

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-cryosparc2#84]
pandas is used at least in the convertOutputStep of 2D classification cryosparc2 protocol, so it should be added to requirements.txt. If not, then one can get the following error:

```
00029:   STARTED: createOutputStep, step 3, time 2021-06-14 11:13:16.795950
00030:   Creating the output...
00031:   Traceback (most recent call last):
00032:     File "/home/josem/work/development/scipion/scipion3/source/core/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 197, in run
00033:       self._run()
00034:     File "/home/josem/work/development/scipion/scipion3/source/core/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _run
00035:       resultFiles = self._runFunc()
00036:     File "/home/josem/work/development/scipion/scipion3/source/core/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 244, in _runFunc
00037:       return self._func(*self._args)
00038:     File "/home/josem/work/development/scipion/scipion3/source/plugins/scipion-em-cryosparc2/cryosparc2/protocols/protocol_cryosparc2d.py", line 282, in createOutputStep
00039:       convertCs2Star(args)
00040:     File "/home/josem/work/development/scipion/scipion3/source/plugins/scipion-em-cryosparc2/cryosparc2/convert/convert.py", line 39, in convertCs2Star
00041:       import pandas as pd
00042:   ModuleNotFoundError: No module named 'pandas'
```

**Comment by delarosatrevin** [comment]
I also think that pyem should be specified in requirements.txt

**Comment by fonsecareyna82** [comment]
It's a bit weird, because when pyem is installed, panda is defined. Could you see if pyem was installed correctly?

**Comment by delarosatrevin** [comment]
I installed the plugin by:

```
git clone plugin-url
python -m pip install -e plugin-folder
```
Then some dependencies were installed (as expected), but not pandas nor pyem. 
I think if we use pandas in our code, it should be specified in the requirements.txt file.

I don't understand why pyem is set in the plugin as a binary but not listen in 'scipion installb --help' output.
